#!/usr/bin/python3
if __name__ == "__main__":
    import calculator_1
    import sys
    argc = len(sys.argv)
    add[] = "+"
    if (argc != 4):
        print("Usage: <a> <operator> <b>".format(sys.argv[0]))
        exit(1)
    else:
        if sys.argv[2] == add[0]:
            print(add)
        elif (sys.argv[2] != "+" or sys.argv[2] != '-' or sys.argv[2] != '*' or sys.argv[2] != '/'):
            print("Unknown operator. Available operators: +, -, * and /")
            exit(1)
        else:
            print(sys.argv[2])
    print(argc)
